# Generated by Django 4.2.6 on 2023-10-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('lead', models.TextField(max_length=500)),
                ('main_text', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
