# Generated by Django 4.2.6 on 2023-10-12 13:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=core.models.image_file_path),
        ),
    ]
