# Generated by Django 4.2.6 on 2023-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('newsy', 'Newsy'), ('felietony', 'Felietony'), ('relacje', 'Relacje'), ('testy', 'Testy')], default='newsy', max_length=255),
        ),
    ]
